<a href="https://colab.research.google.com/github/yennhi-vo/THDEEP/blob/main/Ch%C3%A0o_m%E1%BB%ABng_b%E1%BA%A1n_%C4%91%E1%BA%BFn_v%E1%BB%9Bi_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chào mừng bạn đến với Colab!

In [ ]:
import numpy as np
my_list = [1,9,15,39]
print ('Python list:', my_list)
my_numpy_array = np.array(my_list)
print ('Numpay arry: ', my_numpy_array)

#cach 2
a = np.array([1, 9, 15, 39])
print(a)

#mang 2 chieu
c=np.array([(1,2,3),(4,5,6)])
print(c)
print(c.shape)
print(c.dtype)

#mang  3 chieu
d = np.array([
    [[1.,2.,3.,],[4.,5.,6.]],
    [[7.,8.,9.,],[10,11,12]]
          ])
print(d)
print(d.shape)
print(d.dtype)

3# Tao array voi gia tri ban dau la 0 hoac 1

e = np.zeros((2,3))
f = np.ones((3,3))
print('Zero matrix :\n',e)
print('One matrix :\n',f)


e =np.array([[1.,2.,3.],[4.,5.,6.]])
print(e)
print(e.shape)



Python list: [1, 9, 15, 39]
Numpay arry:  [ 1  9 15 39]
[ 1  9 15 39]
[[1 2 3]
 [4 5 6]]
(2, 3)
int64
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
float64
Zero matrix :
 [[0. 0. 0.]
 [0. 0. 0.]]
One matrix :
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:

e =np.array([[1.,2.,3.],[4.,5.,6.]])
print(e)
print(e.shape)
f= e.reshape(3,2)
print(f)
g = np.array([
    [[1.,2.,3.,],[4.,5.,6.]],
    [[7.,8.,9.,],[10,11,12]]
          ])
print(getattr)
print(g.shape)
h= g.reshape(3,4)
print('reshape (3,4)\n',h)
j= g.reshape(3,2,2)
print('reshape (3,2,2)\n',j)
k= g.reshape(2,3,2)
print('reshape (2,3,2)\n',k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
<built-in function getattr>
(2, 2, 3)
reshape (3,4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3,2,2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2,3,2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


In [ ]:
e =np.array([[1.,2.,3.],[4.,5.,6.]])
f =e.flatten()
print(f)
g = np.array([
    [[1.,2.,3.,],[4.,5.,6.]],
    [[7.,8.,9.,],[10,11,12]]
          ])
j=g.flatten()
print(j)




[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [ ]:
f=np.array([1.,2.,3.,])
g=np.array([4.,5.,6.,])
h_stack = np.hstack((f,g))
print('Horizontal Appen\n',h_stack)
v_stack = np.vstack((f,g))
print('Vertical Appen\n',v_stack)

In [ ]:
a = np.random.randint(100, size(5,))
print('Random 1-D array\n',a)
b = np.random.randint(100, size=(3,4))
print('Random 2-D array\n',b)
c = np.random.randint(100, size=(3,4,3))
print('Random 3-D array\n',c)

In [ ]:
a = np.random.rand(5)
print('Random 1-D array\n',a)
b= np.random.rand(3,4)
print('Random 2-D array\n',b)
c= np.random.rand(3,4,3)
print('Random 3-D array\n',c)

In [ ]:
a = np.random.normal(5,0.5,10)
print(a)

In [ ]:
a=np.random.choice([2,4,6,8,10,12,14,16,18,20])
print(a)
b=np.random.choice([2,4,6,8,10,12,14,16,18,20],size=(3,5))
print(b)

10
[[12  2 14 18 18]
 [16 10  8 18 12]
 [16  4  8 20 18]]


In [ ]:
import numpy as np
a = np.array([(1,2,3),(4,5,6)])
print(a)
print('first row', a[0])
print('second row',a[1])

print('Second column:', a[:,1])
print('fisrt column: ', a[:, 0])
print('first two values of second row:', a[1,:2])


[[1 2 3]
 [4 5 6]]
first row [1 2 3]
second row [4 5 6]
Second column: [2 5]
fisrt column:  [1 4]
first two values of second row: [4 5]


In [1]:
import pandas as pd


# Tạo Series cơ bản
a = pd.Series([1., 2., 3.])
print(a[0]) # Truy cập phần tử đầu tiên

# Tạo Series với chỉ số (index) tùy chỉnh
b = pd.Series([1., 2., 3.], index=['a', 'b', 'c'])
print(b)
print('First value', b['a'])
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)

1.0
a    1.0
b    2.0
c    3.0
dtype: float64
First value 1.0


In [3]:
import numpy as np

# Từ Numpy sang Pandas
h = np.array([[1, 2], [3, 4]])
df_h = pd.DataFrame(h)
print('Data Frame',df_h)
# Từ Pandas sang Numpy
numpy_h = np.array(df_h)

Data Frame    0  1
0  1  2
1  3  4
